[phases.setup]
nix_pkgs = ["python310", "nodejs"]

[phases.install]
nix_pkgs = ["python310Packages.pip"]

[phases.build]
commands = ["pip install -r requirements.txt", "npm install", "npm run build"]

[phases.start]
commands = ["concurrently \"npm run next-start\" \"python -m flask --app api/index run --host 0.0.0.0 --port $PORT\""]
